# Generated by Django 2.0.7 on 2018-10-11 06:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20181009_0656'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserCommands',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('command', models.CharField(max_length=50)),
                ('status', models.BigIntegerField()),
                ('fromuser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.User')),
            ],
        ),
        migrations.AddField(
            model_name='sensordata',
            name='triggered',
            field=models.BigIntegerField(default='0'),
        ),
    ]
