# Generated by Django 2.0.7 on 2018-11-09 08:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20181011_0612'),
    ]

    operations = [
        migrations.CreateModel(
            name='CameraTrigger',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('choice', models.BigIntegerField()),
                ('sent', models.BigIntegerField()),
                ('photo', models.ImageField(default='pic_folder/None', upload_to='pic_folder')),
                ('touser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.User')),
            ],
        ),
    ]
