# Generated by Django 2.0.7 on 2018-11-21 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_cameratrigger'),
    ]

    operations = [
        migrations.AddField(
            model_name='sensordata',
            name='attached_status',
            field=models.BigIntegerField(default=0),
            preserve_default=False,
        ),
    ]
