# Generated by Django 2.0.7 on 2019-04-03 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_healthsensordata_msensordata'),
    ]

    operations = [
        migrations.AddField(
            model_name='sensordata',
            name='shouldActivate',
            field=models.IntegerField(default=0),
        ),
    ]
