# Generated by Django 2.0.7 on 2019-04-03 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_sensordata_shouldactivate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sensordata',
            name='date',
            field=models.DateTimeField(default='0'),
        ),
    ]
