# Generated by Django 2.0.7 on 2019-04-16 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_auto_20190403_1426'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='ageCategory',
            field=models.IntegerField(default=0),
        ),
    ]
