# Generated by Django 2.0.7 on 2019-04-16 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_user_agecategory'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='deseaseCategory',
            field=models.IntegerField(default=0),
        ),
    ]
