# Generated by Django 2.0.7 on 2019-04-16 10:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_user_deseasecategory'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='deseaseCategory',
            new_name='diseaseCategory',
        ),
    ]
